export const FORM_DATA = [
  {
    page: 1,
    subHeading: "Personal Information",
    questionData: [
      {
        id: 1,
        title: "Enter your Name",
        required: true,
        value: "name",
        type: "textfield",
        inputType: "text",
        errorMsg: "Name is required",
      },
      {
        id: 2,
        title: "Enter your Roll Number",
        required: true,
        value: "roll_no",
        type: "textfield",
        inputType: "text",
        errorMsg: "Roll Number is required",
      },
      {
        id: 3,
        title: "Enter your Registration Number",
        required: true,
        value: "reg_no",
        type: "textfield",
        inputType: "text",
        errorMsg: "Registration Number is required",
      },
      {
        id: 4,
        title: "Enter your Personal Email ID",
        required: true,
        value: "email_id",
        type: "textfield",
        inputType: "email",
        errorMsg: "Email is Invalid",
      },
      {
        id: 5,
        title: "Enter your Phone Number (Preferably WhatsApp)",
        required: true,
        value: "phone",
        type: "textfield",
        inputType: "number",
        errorMsg: "Phone Number is required",
      },
      {
        id: 6,
        title: "Link to your Github Profile.",
        required: false,
        value: "github",
        type: "textfield",
        inputType: "text",
      },
      {
        id: 7,
        title: "Link to your Linkedin Profile.",
        required: false,
        value: "linkedin",
        type: "textfield",
        inputType: "text",
      },
    ],
  },
  {
    page: 2,
    subHeading: "Personal Information",
    questionData: [
      {
        id: 1,
        title: "Give a brief introduction of yourself.",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    page: 3,
    subHeading: "Skills",
    questionData: [
      {
        id: 1,
        title: "Tick the roles you are interested in:",
        options: [
          { id: "web_dev", option: "Web Development" },
          { id: "gd", option: "Graphic Design" },
          { id: "vid_edit", option: "Video Editing" },
          { id: "alumini_outreach", option: "Alumni Outreach" },
          { id: "event_man", option: "Event Management" },
          { id: "app_dev", option: "App Development" },
          { id: "content_writing", option: "Content Writing" },
        ],
        type: "checkbox",
        required: true,
      },
      {
        id: 2,
        title: "Give the preference order of the roles you are interested in.",
        type: "textfield",
        value: "pref_order",
        required: true,
      },
      {
        id: 3,
        title:
          "What tech-stack/softwares/tools you use and rate your command on them on a scale of 1-10.",
        type: "textarea",
        value: "tech_stack",
        required: true,
      },
      {
        id: 4,
        title:
          "Give links of some of your previous works related to the roles you are applying for.",
        type: "textfield",
        value: "prev_links",
        required: false,
      },
    ],
  },
  {
    page: 4,
    subHeading: "Self Assessment",
    questionData: [
      {
        id: 1,
        title: "Rate yourself on the scale of 1-10 on following skills : ",
        options: [
          { id: 1, value: "hardwork", option: "Hardworking" },
          { id: 2, value: "teamwork", option: "Team Work" },
          { id: 3, value: "humor", option: "Sense of Humor" },
          { id: 4, value: "punctual", option: "Punctual" },
          { id: 5, value: "creative", option: "Creativity" },
          { id: 6, value: "prob_solving", option: "Problem Solving Skill" },
          { id: 7, value: "responsible", option: "Responsibility" },
        ],
        type: "range",
        fieldType: "range",
      },
    ],
  },
];
